default_context:
  project_name: 'PI01_DATA03'
  project_slug: 'pi01_data03'
  domain_main: 'pi01_data03.com'
  domain_staging: 'stag.pi01_data03.com'
  docker_swarm_stack_name_main: 'pi01_data03-com'
  docker_swarm_stack_name_staging: 'stag-pi01_data03-com'
  secret_key: 'b82eab566e2632f7b39340934803d7572b03584d51fc3659b7354fc34ebd19fd'
  first_superuser: 'admin@pi01_data03.com'
  first_superuser_password: '6388228f5f4ce85981a4e2e7d5a0031e65eeac38d8d31ef21b7647069e684eb8'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.pi01_data03.com", "https://stag.pi01_data03.com", "https://pi01_data03.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@pi01_data03.com'
  postgres_password: '152ceb8835974631cf4f8181b6f2f01e5c7350896ff965d4b16e0d29f540afb2'
  pgadmin_default_user: 'admin@pi01_data03.com'
  pgadmin_default_user_password: 'd088b42d281efc67af6a4320e904c5cae7c43a9a1cb622b270492d794f7cd520'
  traefik_constraint_tag: 'pi01_data03.com'
  traefik_constraint_tag_staging: 'stag.pi01_data03.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:6388228f5f4ce85981a4e2e7d5a0031e65eeac38d8d31ef21b7647069e684eb8'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
